[workspace]
resolver = "2"
members = ["crates/*", "xtask"]
default-members = ["crates/*"]

[workspace.package]
edition = "2024"
authors = ["{{ author_full }}"]
license = "MIT"
repository = "https://github.com/aisamji/{{ project-name }}"

[workspace.dependencies]
clap = "4.5.36"

